# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 8
  - name: DIETClassifier
    entity_recognition: False
    use_masked_language_model: False
    epochs: 300
    constrain_similarities: true
  - name: RegexEntityExtractor
    case_sensitive: True
    use_lookup_tables: True
    use_regexes: True
    use_word_boundaries: True
  - name: LexicalSyntacticFeaturizer
    features:
      - [EOS, digit]
      - [EOS, title, upper, low]
  - name: "CRFEntityExtractor"
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 200
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_my_fallback"
    enable_fallback_prediction: False
  - name: UnexpecTEDIntentPolicy
    max_history: 10
    epochs: 200
  - name: TEDPolicy
    max_history: 10
    epochs: 200
    constrain_similarities: true
  
  
